### PR TITLE
OPS-2301 Add missing entries in account-mapping.yml

### PR DESCRIPTION
**Pull request by alexharv074**
The account-mapping.yml only had a single entry in it. This extends it
to include all mappings from config.j2 file that had been added recently
in the docker-ubuntu-aws-cli project.

### CODE REVIEW

**Comment by alexharv074** [comment]
I am confused why the build is failing. Not related to my change I think?

**Comment by benjamin-tucker** [comment]
AWS things shouldn't be in the base

**Comment by alexharv074** [comment]
@benjamin-tucker Maybe AWS things should not be in the base however, they are, and they always have been. If you would like to raise a Jira about a massive refactor to move everything that's fine, but it has nothing to do with this PR or the fact that this is all broken.

**Comment by alexharv074** [comment]
I see that Sajid already added another version of account-mapping.yml in the AWS CLI container, but has not removed it from here. Therefore I have refactored this PR to clean up after that, and we can use account-mapping.yml in the other container.

**Comment by alexharv074** [comment]
Actually on thinking of this further, Sajid may have wanted the original account-mapping.yml file to stay here so that in principle it can still be used without the docker-ubuntu-aws-cli layer. Ok, closing.

**Pull request closed without merging**
